package mapreduce

import (
	"encoding/json"
	"hash/fnv"
	"io/ioutil"
	"os"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//

	// firstly, read the file
	content, err := ioutil.ReadFile(inFile)
	if err != nil {
		panic(err)
	}
	// use mapF function to convert every word in the file to { "word" : "1" }
	kvs := mapF(inFile, string(content))
	// make a 2-dimension vector to store kvs
	res := make([][]KeyValue, nReduce)
	for _, kv := range kvs {
		// use the given hash function to calculate where the key should be in the kvs vector
		r := ihash(kv.Key) % nReduce
		// append it to res
		res[r] = append(res[r], kv)
	}

	for i := 0; i < nReduce; i++ {
		// get the intermediate file name
		fileName := reduceName(jobName, mapTask, i)
		// create that file
		file, err := os.Create(fileName)
		if err != nil {
			panic(err)
		}
		// init a encoder like comments above said
		enc := json.NewEncoder(file)
		// encode every single kv
		for _, kv := range res[i] {
			err := enc.Encode(&kv)
			if err != nil {
				panic(err)
			}
		}
		err = file.Close()
		if err != nil {
			panic(err)
		}
	}

}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	return int(h.Sum32() & 0x7fffffff)
}
